#!/bin/bash -I
#
# Job name:
#SBATCH --job-name=PSF100nm
#
# Error file:
#SBATCH --error=ERR_PSF_window_100nm
#
# Account:
#SBATCH  --account=ac_etci
#
# Partition
#SBATCH --partition=lr3
#
# QoS:
#SBATCH --qos=lr_normal
#
# Processors:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
# Wall clock limit:
#SBATCH --time=01:30:00
#
# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=ygzhang@lbl.gov
#

module load matlab
MatlabDir=/global/scratch/ygzhang/PyBeamDiag/matlab
cd $MatlabDir
matlab -nodisplay -nosplash -r "TRACK_recon_100nm"

PyBeamDiagDir=/global/scratch/ygzhang/PyBeamDiag
cd $PyBeamDiagDir
python PSF_window_100nm.py

FAIL=n
for job in `jobs -p`
do
echo $job
    wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
echo "YAY!"
else
echo "FAIL! ($FAIL)"
fi
