#!/bin/bash -I
#
# Job name:
#SBATCH --job-name=60nm_par
#
# Error file:
#SBATCH --error=ERR_par_parsing_60nm
#
# Account:
#SBATCH  --account=ac_etci
#
# Partition
#SBATCH --partition=lr3
#
# QoS:
#SBATCH --qos=lr_normal
#
# Processors:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
# Wall clock limit:
#SBATCH --time=72:00:00
#
# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=ygzhang@lbl.gov
#

PyBeamDiagDir=/global/scratch/ygzhang/PyBeamDiag
cd $PyBeamDiagDir
python PARSING_60nm.py
# python -m memory_profiler /global/scratch/ygzhang/PyBeamDiag/PARSING_60nm.py > MEM_parsing_60nm

FAIL=0
for job in `jobs -p`
do
echo $job
    wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
echo "YAY!"
else
echo "FAIL! ($FAIL)"
fi
