#!/bin/bash -I
#
# Job name:
#SBATCH --job-name=60nm_pixelP
#
# Account:
#SBATCH  --account=ac_etci
#
# Partition
#SBATCH --partition=lr3
#
# QoS:
#SBATCH --qos=lr_normal
#
# Processors:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
# Wall clock limit:
#SBATCH --time=72:00:00
#
# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=ygzhang@lbl.gov
#

PyBeamDiagDir=/global/scratch/ygzhang/PyBeamDiag
MatlabDir=/global/scratch/ygzhang/PyBeamDiag/matlab

step=60nm
plane=pixelP

if  [ $plane == backP ]; then
    facing=bottom
elif  [ $plane == pixelP ]; then
    facing=top
else
    echo 'WRONG $plane !!!'
    echo "plane = $plane"
fi
fitsDir=fits_${plane}
pickle=PSF_${step}_${plane}

echo "  step  = $step"
echo " plane  = $plane"
echo "facing  = $facing"
echo "fitsDir = $fitsDir"
echo "pickle  = $pickle"


echo 'parsing G4 output'
cd $PyBeamDiagDir
python PARSING.py        $step     $fitsDir    $facing              # args: | step length | fits directory | pixel-plane facing |

echo 'track reconstruction' 
cd $MatlabDir
matlab -nodisplay -nosplash -r "TRACK_recon     $step     $fitsDir"         # args: | step length | fits directory |

echo 'compute PSF at window'
cd $PyBeamDiagDir
python PSF_window.py    $step     $fitsDir    $pickle      # args: | step length | fits directory | outName: %s.p |

echo 'Done'

FAIL=0
for job in `jobs -p`
do
echo $job
    wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
echo "YAY!"
else
echo "FAIL! ($FAIL)"
fi
