#!/bin/bash -I
#
# Job name:
#SBATCH --job-name=100nm
#
# Account:
#SBATCH  --account=ac_etci
#
# Partition
#SBATCH --partition=lr3
#
# QoS:
#SBATCH --qos=lr_normal
#
# Processors:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
# Wall clock limit:
#SBATCH --time=72:00:00
#
# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=ygzhang@lbl.gov
#

G4OutDir=/global/scratch/ygzhang/G4BeamDiag/step_size/out_LRC/100nm
PyBeamDiagDir=/global/scratch/ygzhang/PyBeamDiag
MatlabDir=/global/scratch/ygzhang/PyBeamDiag/matlab

echo 'running G4'
cd $G4OutDir
../../build_LRC/exe_BeamDiag ../../macro/100nm.mac

echo 'splitting G4 output'
cd $PyBeamDiagDir
python myText_100nm.py

echo 'parsing G4 output'
python PARSING_100nm.py

echo 'track reconstruction' 
cd $MatlabDir
matlab -nodisplay -nosplash -r 'TRACK_recon_100nm'

echo 'compute PSF at window'
cd $PyBeamDiagDir
python PSF_window_100nm.py

echo 'Done'

FAIL=0
for job in `jobs -p`
do
echo $job
    wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
echo "YAY!"
else
echo "FAIL! ($FAIL)"
fi
