binsPB = np.arange(-20,20,0.5)
figPB, axPB = plt.subplots(figsize=(10,8))
axPB.hist(edataAfterPointBack.back_projection, bins=binsPB, histtype='stepfilled',\
         align='left',color='g', label='After direction cut',alpha=0.5)
#axPB.legend()
axPB.set_xlim(-22, 22)
axPB.set_ylim(0, 240)
axPB.set_xlabel('Position of where electrons are produced (mm)')
axPB.set_ylabel('Counts')
figPB.show()