fig, ax = plt.subplots()
eCut = np.arange(0, 1600, 100)
ax.plot(eCut, ratioIn, 'b', label='Peak-to-Total. Total is counted after e- energy cut')
ax.plot(eCut, ratioInOverTotal, 'r', label='Peak-to-Total.')
ax.legend(loc=2)
ax.set_xlabel('Cut on Electron Energy (keV)')
ax.set_ylabel('Ratio')
ax.set_ylim(ymin=0)
fig.show()